#define PIN_BUZZER 26
#define PIN_LED_RED 23
#define PIN_LED_BLUE 18
#define PIN_LED_GREEN 22
#define PIN_RELAY 14
#define PIN_SERVO 5

#define CERO_DEG_VALUE 1000
#define ONE_HUNDRED_EIGHTY_DEG_VALUE 2000
#define STANDARD_PERIOD_HERTZ 50

#define ONE_HUNDRED_EIGHTY_DEG 180
#define CERO_DEG 0