#define PIN_BUZZER 26
#define PIN_LED_RED 23
#define PIN_LED_BLUE 18
#define PIN_LED_GREEN 22
#define PIN_RELAY 14
#define PIN_SERVO 5

#define CERO_DEG_VALUE 1000
#define ONE_HUNDRED_EIGHTY_DEG_VALUE 2000
#define STANDARD_PERIOD_HERTZ 50

#define ONE_HUNDRED_EIGHTY_DEG 180
#define CERO_DEG 0

#define RED_RED_COLOR_VALUE 255
#define RED_GREEN_COLOR_VALUE 0
#define RED_BLUE_COLOR_VALUE 0

#define ORANGE_RED_COLOR_VALUE 255
#define ORANGE_GREEN_COLOR_VALUE 165
#define ORANGE_BLUE_COLOR_VALUE 0

#define YELLOW_RED_COLOR_VALUE 255
#define YELLOW_GREEN_COLOR_VALUE 255
#define YELLOW_BLUE_COLOR_VALUE 0

#define GREEN_RED_COLOR_VALUE 0
#define GREEN_GREEN_COLOR_VALUE 255
#define GREEN_BLUE_COLOR_VALUE 0