#define BEGIN_SERIAL_PORT 115200

#define CO2_KEY "CO2"
#define DIST_KEY "DIST"
#define HUM_KEY "HUM"
#define TEMP_KEY "TEMP"
#define OPEN_DOOR_KEY "OPEN_DOOR"
#define STATE_KEY "STATE"
#define BUZZER_KEY "BUZZER"
#define RELAY_KEY "RELAY"

typedef int STATE_VALUES;
const STATE_VALUES CO2_HIGH_PORCENT = 5;
const STATE_VALUES TEMP_HIGH = 35;
const STATE_VALUES CO2_HIGH = 1000;
const STATE_VALUES MIN_HUM_HIGH = 20;
const STATE_VALUES MAX_HUM_HIGH = 70;

const STATE_VALUES TEMP_MID = 32;
const STATE_VALUES CO2_MID = 600;
const STATE_VALUES MIN_HUM_MID = 30;
const STATE_VALUES MAX_HUM_MID = 60;

const STATE_VALUES TEMP_LOW = 24;
const STATE_VALUES CO2_LOW = 300;
const STATE_VALUES MIN_HUM_LOW = 35;
const STATE_VALUES MAX_HUM_LOW = 50;
const STATE_VALUES DIST_LOW = 5;
const STATE_VALUES DIST_ERROR = 50;

typedef int STATE;
const STATE INIT_STATE = 0;
const STATE L_STATE = 1;
const STATE M_STATE = 2;
const STATE H_STATE = 3;
const STATE C_STATE = 4;
const int MAX_STATES = 5;

const STATE L_DIST_STATE = 0;
const STATE M_DIST_STATE = 1;
const STATE L_TEMP_STATE = 0;
const STATE M_TEMP_STATE = 1;
const STATE H_TEMP_STATE = 2;
const STATE C_TEMP_STATE = 3;
const STATE L_HUM_STATE = 0;
const STATE M_HUM_STATE = 1;
const STATE H_HUM_STATE = 2;
const STATE C_HUM_STATE = 3;
const STATE L_CO2_STATE = 0;
const STATE M_CO2_STATE = 1;
const STATE H_CO2_STATE = 2;
const STATE C_CO2_STATE = 3;

typedef int EVENT;
const EVENT INIT_EVENT = 0;
const EVENT L_EVENT = 1;
const EVENT M_EVENT = 2;
const EVENT H_EVENT = 3;
const EVENT C_EVENT = 4;
const EVENT CO2_C_EVENT = 5;
const EVENT CO2_H_EVENT = 6;
const EVENT CO2_M_EVENT = 7;
const EVENT CO2_L_EVENT = 8;
const EVENT DIST_M_EVENT = 9;
const EVENT DIST_L_EVENT = 10;
const EVENT MIN_HUM_C_EVENT = 11;
const EVENT MAX_HUM_C_EVENT = 12;
const EVENT MIN_HUM_H_EVENT = 13;
const EVENT MAX_HUM_H_EVENT = 14;
const EVENT MIN_HUM_M_EVENT = 15;
const EVENT MAX_HUM_M_EVENT = 16;
const EVENT MAX_HUM_L_EVENT = 17;
const EVENT TEMP_C_EVENT = 18;
const EVENT TEMP_H_EVENT = 19;
const EVENT TEMP_M_EVENT = 20;
const EVENT TEMP_L_EVENT = 21;
const EVENT NONE_EVENT = 22;
const int MAX_EVENTS = 23;

typedef int EVENTS_GROUPS;
const EVENTS_GROUPS SENSORS_EVENTS = 0;
const EVENTS_GROUPS EMBED_EVENTS = 1;
const int NOTIFY_STATUS_EVENT = 2;
const int EVENTS_GROUPS_COUNT = 3;

typedef int SENSOR;
const SENSOR CO2_SENSOR = 0;
const SENSOR DIST_SENSOR = 1;
const SENSOR HUM_SENSOR = 2;
const SENSOR TEMP_SENSOR = 3;
const int SENSORS_COUNT = 4;
